global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using InventoryManagementApp.Data;
global using InventoryManagementApp.Services.Core;
global using InventoryManagementApp.Models.ImportExport;
global using Microsoft.Extensions.DependencyInjection;
global using ItemModel = InventoryManagementApp.Models.Domain.ItemModel;
global using CustomerModel = InventoryManagementApp.Models.Domain.Customer;
global using RentalModel = InventoryManagementApp.Models.Domain.Rental;
